// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwBJUYfzJftOez7WMeFPNILC9x_7Tyno',
    appId: '1:446408956773:web:b004af88c4dd7cf2151f8c',
    messagingSenderId: '446408956773',
    projectId: 't3ebt-c2f8a',
    authDomain: 't3ebt-c2f8a.firebaseapp.com',
    storageBucket: 't3ebt-c2f8a.firebasestorage.app',
    measurementId: 'G-SN7L35BLVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4FodBXvnVD07-R9abmY63pKaq1YQm4tQ',
    appId: '1:446408956773:android:c20eff4b97d87b91151f8c',
    messagingSenderId: '446408956773',
    projectId: 't3ebt-c2f8a',
    storageBucket: 't3ebt-c2f8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF947kZzvcAlYdZO-wJg2HrFlO26KETmU',
    appId: '1:446408956773:ios:c44f608db3e85432151f8c',
    messagingSenderId: '446408956773',
    projectId: 't3ebt-c2f8a',
    storageBucket: 't3ebt-c2f8a.firebasestorage.app',
    iosClientId: '446408956773-jougi4ua4nmtjo333r42ibkgk44kffuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.a7lili',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF947kZzvcAlYdZO-wJg2HrFlO26KETmU',
    appId: '1:446408956773:ios:c44f608db3e85432151f8c',
    messagingSenderId: '446408956773',
    projectId: 't3ebt-c2f8a',
    storageBucket: 't3ebt-c2f8a.firebasestorage.app',
    iosClientId: '446408956773-jougi4ua4nmtjo333r42ibkgk44kffuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.a7lili',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuwBJUYfzJftOez7WMeFPNILC9x_7Tyno',
    appId: '1:446408956773:web:e4db2c2528d73f13151f8c',
    messagingSenderId: '446408956773',
    projectId: 't3ebt-c2f8a',
    authDomain: 't3ebt-c2f8a.firebaseapp.com',
    storageBucket: 't3ebt-c2f8a.firebasestorage.app',
    measurementId: 'G-8CCDZ67BGN',
  );

}